<?php
require_once "SistemaFCE/dao/DaoBase.class.php";
class DaoResourcesSubprojects extends DaoBase{

    public function save(ResourcesSubprojects &$elem)
    {
        if($elem->getId()==null)
            $elem->setCreated(time());

        $elem->setUpdated(time());
        return parent::save($elem); // TODO: Change the autogenerated stub
    }

    public function findDemandados() {
        $c = $this->getCriterioBase();
        $c->add(Restricciones::like('status',"carencia"));
        $limit= 5;
        //function getFindBySql($filtro = null,$order=null,$limitCount=null,$limitOffset=null,$group=null)
        $lista = $this->findBy($c, null,$limit,$limit);
        foreach($lista as $elem) {
            $listaSimple[$elem->getResourceId()] = $elem;
        }
        return $listaSimple;
    }
}